PLUGIN_NAME=		realtek-re198
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Realtek re(4) vendor driver
PLUGIN_MAINTAINER=	franco@opnsense.org
PLUGIN_DEPENDS=		realtek-re-kmod198

.include "../../Mk/plugins.mk"
